/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteMemberNumberRouteImport } from './routes/invite.$memberNumber'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin.members'
import { Route as AuthenticatedAdminInvitesRouteImport } from './routes/_authenticated/admin.invites'
import { Route as AuthenticatedAdminInviteSharesRouteImport } from './routes/_authenticated/admin.invite-shares'
import { Route as AuthenticatedAdminBenefitsRouteImport } from './routes/_authenticated/admin.benefits'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteMemberNumberRoute = InviteMemberNumberRouteImport.update({
  id: '/invite/$memberNumber',
  path: '/invite/$memberNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvitesRoute =
  AuthenticatedAdminInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInviteSharesRoute =
  AuthenticatedAdminInviteSharesRouteImport.update({
    id: '/invite-shares',
    path: '/invite-shares',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBenefitsRoute =
  AuthenticatedAdminBenefitsRouteImport.update({
    id: '/benefits',
    path: '/benefits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/vip': typeof VipRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/invite/$memberNumber': typeof InviteMemberNumberRoute
  '/admin/benefits': typeof AuthenticatedAdminBenefitsRoute
  '/admin/invite-shares': typeof AuthenticatedAdminInviteSharesRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/vip': typeof VipRoute
  '/invite/$memberNumber': typeof InviteMemberNumberRoute
  '/admin/benefits': typeof AuthenticatedAdminBenefitsRoute
  '/admin/invite-shares': typeof AuthenticatedAdminInviteSharesRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/vip': typeof VipRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/invite/$memberNumber': typeof InviteMemberNumberRoute
  '/_authenticated/admin/benefits': typeof AuthenticatedAdminBenefitsRoute
  '/_authenticated/admin/invite-shares': typeof AuthenticatedAdminInviteSharesRoute
  '/_authenticated/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/vip'
    | '/admin'
    | '/invite/$memberNumber'
    | '/admin/benefits'
    | '/admin/invite-shares'
    | '/admin/invites'
    | '/admin/members'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/vip'
    | '/invite/$memberNumber'
    | '/admin/benefits'
    | '/admin/invite-shares'
    | '/admin/invites'
    | '/admin/members'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/vip'
    | '/_authenticated/admin'
    | '/invite/$memberNumber'
    | '/_authenticated/admin/benefits'
    | '/_authenticated/admin/invite-shares'
    | '/_authenticated/admin/invites'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  VipRoute: typeof VipRoute
  InviteMemberNumberRoute: typeof InviteMemberNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$memberNumber': {
      id: '/invite/$memberNumber'
      path: '/invite/$memberNumber'
      fullPath: '/invite/$memberNumber'
      preLoaderRoute: typeof InviteMemberNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invites': {
      id: '/_authenticated/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AuthenticatedAdminInvitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invite-shares': {
      id: '/_authenticated/admin/invite-shares'
      path: '/invite-shares'
      fullPath: '/admin/invite-shares'
      preLoaderRoute: typeof AuthenticatedAdminInviteSharesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/benefits': {
      id: '/_authenticated/admin/benefits'
      path: '/benefits'
      fullPath: '/admin/benefits'
      preLoaderRoute: typeof AuthenticatedAdminBenefitsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBenefitsRoute: typeof AuthenticatedAdminBenefitsRoute
  AuthenticatedAdminInviteSharesRoute: typeof AuthenticatedAdminInviteSharesRoute
  AuthenticatedAdminInvitesRoute: typeof AuthenticatedAdminInvitesRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBenefitsRoute: AuthenticatedAdminBenefitsRoute,
  AuthenticatedAdminInviteSharesRoute: AuthenticatedAdminInviteSharesRoute,
  AuthenticatedAdminInvitesRoute: AuthenticatedAdminInvitesRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  VipRoute: VipRoute,
  InviteMemberNumberRoute: InviteMemberNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
